#!/bin/bash

if [ -z $1 ]; then
  echo -e "Delete a site\n\nUsage:\n"
  echo "  delete [domain]           Delete site"
  echo "  delete [domain] [folder]  Delete child site"
  echo
  exit
fi

SCRIPTPATH=$(dirname $(readlink -f "$0"))
. $SCRIPTPATH/common

DOMAIN_NAME=$1
SUBFOLDER=$2

if [ -z "$SUBFOLDER" ]; then

  echo "Deleting site at $DOMAIN_NAME"
  enter-when-ready

  sudo site $DOMAIN_NAME -delete=force

  if [ -L ~/apps/$DOMAIN_NAME ]; then
    rm ~/apps/$DOMAIN_NAME
  fi

  echo -e "\nSite deleted from ~/apps/$DOMAIN_NAME"

  exit
fi


# Subfolder of existing site

echo "Deleting child site at $DOMAIN_NAME/$SUBFOLDER"
enter-when-ready

PARENT_SITE_PATH=~/apps/$DOMAIN_NAME

if [ ! -L $PARENT_SITE_PATH ]; then
  echo "Parent site not found: $PARENT_SITE_PATH"
  exit
fi

CHILD_SITE_PATH=$PARENT_SITE_PATH/$SUBFOLDER

if [ ! -d $CHILD_SITE_PATH ]; then
  echo "Site not found: $CHILD_SITE_PATH"
  exit
fi

sudo site $DOMAIN_NAME -subfolder="/$SUBFOLDER" -delete=force

echo -e "\nSite deleted from $CHILD_SITE_PATH"
