#!/bin/bash

# if [ -z $1 ]; then
#   echo -e "Get information about a site\n\nUsage:"
#   echo "  info                    Info about system"
#   echo "  info [domain]           Info about site"
#   echo "  info [domain] [folder]  Info about child site"
#   echo
#   exit
# fi

SCRIPTPATH=$(dirname $(readlink -f "$0"))
. $SCRIPTPATH/common

DOMAIN_NAME=$1

if [ -z "$DOMAIN_NAME" ]; then
  echo "System information"
  sudo webinoly -info
  exit
fi

SUBFOLDER=$2

if [ -z "$SUBFOLDER" ]; then
  echo "Site information: $DOMAIN_NAME"
  sudo site $DOMAIN_NAME -info
  exit
fi


# Subfolder of existing site

echo "Site information: $DOMAIN_NAME/$SUBFOLDER"

sudo site $DOMAIN_NAME -subfolder=/$SUBFOLDER -info
