#!/usr/bin/env bash
set -eou pipefail

# Get absolute path this script is in, for example: /home/$USER/bin
SCRIPTPATH=$(dirname $(readlink -f "$0"))
. $SCRIPTPATH/common

echo -e "Installing system features\n"

if [[ $EUID -eq 0 ]]; then

  if ! id ubuntu >/dev/null 2>&1; then

    echo -e "Creating default user \"ubuntu\""
    enter-when-ready

    sudo adduser --disabled-password --gecos '' ubuntu
    sudo usermod -aG sudo ubuntu

    ### Disable sudo password

    sudo cp /etc/sudoers /etc/sudoers.bak
    sudo bash -c "echo 'ubuntu ALL=(ALL) NOPASSWD: ALL' | (EDITOR='tee -a' visudo)"
    sudo bash -c "echo 'www-data ALL=(ALL) NOPASSWD: ALL' | (EDITOR='tee -a' visudo)"

    ### Add SSH public key

    rsync --archive --chown=ubuntu:ubuntu ~/.ssh /home/ubuntu

    sudo -u ubuntu -H bash -c "chmod 700 ~/.ssh"
    sudo -u ubuntu -H bash -c "chmod 600 ~/.ssh/authorized_keys"

  fi

  echo -e "\nEnter \"exit\" to log out from this session, then login with user ubuntu\n"
  exit
fi

if [ ! -f ~/.bash_aliases ]; then

  echo -e "Set up shell environment"
  enter-when-ready

  mkdir -p ~/apps
  mkdir -p ~/bin
  mkdir -p ~/logs

  cp $SCRIPTPATH/assets/.profile ~
  cp $SCRIPTPATH/assets/.bash_aliases ~

  # Remove welcome message on SSH login
  touch ~/.hushlogin

  # Cron job report wrapper - See ./assets/crontab-template.txt
  cp $SCRIPTPATH/assets/cronic ~/bin

  # Move installed folder
  mv $SCRIPTPATH ~/bin/systra
  ln -s ~/bin/systra/sys ~/bin/sys

  sudo apt update && sudo apt -y upgrade

  # Snap required for webinoly
  sudo apt-get install fuse
  sudo apt install snapd
  sudo systemctl unmask snapd.service
  sudo systemctl enable snapd.service
  sudo systemctl start snapd.service

  sudo apt install git

  # Terminal-based text editor 
  sudo apt install nano
  # curl https://getmic.ro | bash # https://github.com/zyedidia/micro

  # sudo apt-get update
  sudo apt install trash-cli

  echo -e "\nRun the following command: source ~/.profile && sys install\n"
  echo -e "\nFor legacy server: source ~/.profile && PHP_VER=7.2 sys install\n"
  exit
fi

if [ ! -d /opt/webinoly ]; then

  echo "Install web server - NGINX, MariaDB, PHP"
  echo "This will take a few minutes"
  enter-when-ready

  ### Previously depended on external URL
  # wget -qO weby qrok.es/wy && sudo bash weby 0
  # sudo tar -xf $HOME/webinoly.tar -C /opt/webinoly

  sudo mkdir -p /opt/webinoly

  sudo cp -r $SCRIPTPATH/assets/webinoly/lib /opt/webinoly
  sudo cp -r $SCRIPTPATH/assets/webinoly/templates /opt/webinoly
  sudo cp -r $SCRIPTPATH/assets/webinoly/usr /opt/webinoly

  ### Based on assets/webinoly/weby --->

  sudo mkdir -p /opt/webinoly/templates/source
  sudo find /opt/webinoly -type d -exec chmod 755 {} \;
  sudo find /opt/webinoly -type f -exec chmod 644 {} \;
  sudo chmod -f 744 /opt/webinoly/lib/ex-*

  sudo chmod 755 /opt/webinoly/usr/*
  sudo mv /opt/webinoly/usr/* /usr/bin/

  ### <---

  sudo -u root bash -c 'source /opt/webinoly/lib/general && webinoly -dynvar=app-version -value -value=$app_version' 1> /dev/null

  # Increase upload limit
  sudo webinoly -dynvar=max-mb-uploads -value=200 1> /dev/null

  # Disable XMLRPC - See assets/webinoly/lib/install, nginx_optim()
  # Updates /etc/nginx/common/wpcommon.conf, /etc/nginx/common/wpcommon-noauth.conf
  sudo webinoly -dynvar=xmlrpc -value=blocked 1> /dev/null


  # Let user manually enter email
  echo "Email address will be used for sending server error notification - it can be empty"

  # Read input, skip if empty
  echo -n "Enter email address: "
  read EMAIL
  if [ ! -z "$EMAIL" ]; then
    sudo webinoly -email="$EMAIL" 1> /dev/null # Saved in /opt/webinoly/webinoly.conf
  fi

  # Timezone

  # Check if set automatically to local machine
  TIMEZONE=`cat /etc/timezone`
  if [ ! -z "$TIMEZONE" ]; then
    sudo webinoly -timezone=$TIMEZONE
  else
    # List all available timezones
    # See also https://www.php.net/manual/en/timezones.php
    # Or run: ls /usr/share/zoneinfo
    timedatectl list-timezones --no-pager

    # Let user manually enter timezone
    sudo webinoly -timezone
  fi

  if [ -z "${PHP_VER-}" ]; then

    # Default PHP version - No need to call sudo stack
    PHP_VER=8.2

  elif [ "$PHP_VER" == "7.2" ]; then

    # MariaDB >= 10.6 does not support character set "utf8" (must use utf8md3 or utf8md4), which breaks Duplicator packages from legacy servers
    sudo stack -mysql-ver=10.5
  fi

  sudo stack -php-ver=$PHP_VER # assets/webinoly/lib/general, php_supported=(..)

  sudo stack -lemp

  # Allow SFTP access to www-data user
  sudo webinoly -login-www-data=on

  # Disable HTTP Auth
  # sudo httpauth -wp-admin=off 1> /dev/null
  sudo webinoly -dynvar=wp-admin-auth -value=purged 1> /dev/null

  # Allow default user to edit served files

  # Revert change made by assets/webinoly/lib/install, nginx_optim()
  # When it's set to "no", the umask 022 is interpreted as -rw-r--r--
  # When it's set to "yes", it is interpreted as -rw-rw-r-- (Writable by group)
  # We want the latter, so www-data user (PHP process) can modify files created
  # by other users of the group, i.e, ubuntu
  sudo sed -i '/USERGROUPS_ENAB/c \USERGROUPS_ENAB yes' /etc/login.defs

  sudo usermod -aG www-data $USER

  sudo chown -R www-data:www-data /var/www # Was $USER:www-data

  # All new files and directories created under /var/www are owned by the www-data group.

  sudo chgrp -R www-data /var/www
  sudo chmod -R g+rw /var/www

  sudo find /var/www -type d -exec chmod 2775 {} \;
  sudo find /var/www -type f -exec chmod ug+rw {} \;

  # Increase file watch limit - Helps with remote editing large folders
  # https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
  sudo -u root bash -c 'echo -e "\nfs.inotify.max_user_watches=524288\n" >> /etc/sysctl.conf'
  sudo sysctl -p 1> /dev/null

  echo -e "\nIf you need to see MySQL credentials in the future, run: sudo webinoly -dbpass\n"

  # echo -e "\nMake note of the above credentials, then run: sys install\n"
  # exit
fi

if [ ! -f ~/bin/composer ]; then

  echo -e "Install Composer - Package manager for PHP"
  enter-when-ready

  curl https://getcomposer.org/installer -o install-composer.php
  php install-composer.php
  rm install-composer.php
  mv composer.phar ~/bin/composer
fi

if [ ! -f ~/bin/wp ]; then

  echo -e "Install WP-CLI - Command line interface for WordPress"
  enter-when-ready

  curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  php wp-cli.phar --info
  chmod +x wp-cli.phar
  mv wp-cli.phar ~/bin/wp
  echo
fi

if [ ! -d ~/n ]; then

  echo -e "Install Node.js - JavaScript runtime"
  enter-when-ready

  # sudo apt-get update
  sudo apt-get install build-essential
  curl -L https://git.io/n-install | bash

  echo -e "\nRun the following command: source ~/.profile && sys install\n"
  exit
fi

if [ ! -f ~/n/bin/pm2 ]; then

  echo -e "Install PM2 - Process manager for Node.js"
  enter-when-ready

  npm install pm2@latest -g

  # https://pm2.keymetrics.io/docs/usage/startup/
  pm2 startup || true

  # Copy crontab template, replace placeholders, load cron

  cp $SCRIPTPATH/assets/crontab-template.txt ~/crontab-tmp.txt

  EMAIL=$(sudo webinoly -conf-read=mail) # Mail address from /opt/webinoly/webinoly.conf

  if [ -z "$EMAIL" ]; then
    EMAIL="''" # Empty value for crontab
  fi

  sed -i "s/__USER__/$USER/g" ~/crontab-tmp.txt
  sed -i "s/__EMAIL__/$EMAIL/g" ~/crontab-tmp.txt

  crontab ~/crontab-tmp.txt
  rm ~/crontab-tmp.txt

  # PM2 install ends with command: sudo env PATH=$PATH:/home/$USER/n/bin /home/$USER/n/lib/node_modules/pm2/bin/pm2 startup systemd -u $USER --hp /home/$USER
  echo -e "\nRun the above command, then: sys install\n"

  # The following is not necessary because we use "n" to manage Node.js versions,
  # and the symlinked binary is always in the same location
  # echo "If you upgrade Node.js in the future, run: pm2 unstartup && pm2 startup"

  exit
fi

echo -e "System fully installed.\n"
