#!/usr/bin/env bash
set -eou pipefail

if [ -z ${1-} ]; then
  echo -e "Create a new site\n\nUsage:\n"
  echo "  new [domain]              Create new site"
  echo "  new [domain] [folder]     Create new child site"
  echo
  exit
fi

SCRIPTPATH=$(dirname $(readlink -f "$0"))
. $SCRIPTPATH/common

DOMAIN_NAME=$1
SUBFOLDER=${2-}

if [ -z "$SUBFOLDER" ]; then

  echo "Creating site at $DOMAIN_NAME"
  enter-when-ready

  # Create site - Redirect www -> root domain
  sudo site $DOMAIN_NAME -wp -force-redirect=root

  if [ ! -f "/var/www/$DOMAIN_NAME/wp-config.php" ]; then
    echo "Error: Site config not found"
    exit
  fi

  # Don't put wp-admin under HTTP Basic Auth
  sudo httpauth $DOMAIN_NAME -wp-admin=off &> /dev/null

  ln -s /var/www/$DOMAIN_NAME/htdocs ~/apps/$DOMAIN_NAME

  # Move wp-config to app root
  sudo mv /var/www/$DOMAIN_NAME/wp-config.php ~/apps/$DOMAIN_NAME

  # All new files and directories are owned by www-data group - and editable by $USER
  sudo chown -R $USER:www-data /var/www/$DOMAIN_NAME/htdocs
  sudo chmod -R g+rw /var/www/$DOMAIN_NAME/htdocs

  pushd "/home/$USER/apps/$DOMAIN_NAME/" &>/dev/null

  # Remove default plugins
  if [ -d "wp-content/plugins/akismet" ]; then
    rm -rf "/home/$USER/apps/$DOMAIN_NAME/wp-content/plugins/akismet"
  fi
  if [ -f "wp-content/plugins/hello.php" ]; then
    rm "wp-content/plugins/hello.php"
  fi

  echo
  echo -n "Prepare HTTPS (Y/n)? "
  read answer

  if [ "$answer" != "${answer#[Nn]}" ] ;then
    PROTOCOL=http
  else
    PROTOCOL=https
    sudo site $DOMAIN_NAME -ssl=on
    echo "HTTPS enabled"
  fi

  SITE_URL=$PROTOCOL://$DOMAIN_NAME/

  wp core install --url=$SITE_URL --title="Site Title" --admin_user=admin --admin_password=admin --admin_email=admin@example.com
  wp rewrite structure '/%postname%'

  popd

  echo -e "\nSite installed at ~/apps/$DOMAIN_NAME"
  echo "Site URL: $SITE_URL"

  exit
fi


# Subfolder of existing site

if [ ! -L ~/apps/$DOMAIN_NAME ]; then
  echo "Site not found: ~/apps/$DOMAIN_NAME"
  exit
fi

echo "Creating child site at $DOMAIN_NAME/$SUBFOLDER"
enter-when-ready

sudo site $DOMAIN_NAME -subfolder=/$SUBFOLDER -wp -force-redirect=root

if [ ! -f "/home/$USER/apps/$DOMAIN_NAME/$SUBFOLDER/wp-config.php" ]; then
  # Error: Site was not created
  exit
fi

sudo httpauth $DOMAIN_NAME -subfolder=/$SUBFOLDER -wp-admin=off &> /dev/null

# All new files and directories are owned by www-data group - and editable by $USER
# sudo chown -R $USER:www-data /var/www/$DOMAIN_NAME/htdocs/$SUBFOLDER
sudo chmod -R g+rw /var/www/$DOMAIN_NAME/htdocs/$SUBFOLDER

pushd "/home/$USER/apps/$DOMAIN_NAME/$SUBFOLDER/" &>/dev/null

# Remove default plugins
if [ -d "wp-content/plugins/akismet" ]; then
  rm -rf "wp-content/plugins/akismet"
fi
if [ -f "wp-content/plugins/hello.php" ]; then
  rm "wp-content/plugins/hello.php"
fi

PROTOCOL=http # TODO: If parent site has SSL already, PROTOCOL=https

SITE_URL=$PROTOCOL://$DOMAIN_NAME/$SUBFOLDER/

wp core install --url=$SITE_URL --title="Site Title" --admin_user=admin --admin_password=admin --admin_email=admin@example.com
wp rewrite structure '/%postname%'

popd &>/dev/null

echo
echo "Site folder is ~/apps/$DOMAIN_NAME/$SUBFOLDER"
echo "Site URL is $SITE_URL"
