#!/bin/bash

if [ -z $1 ]; then
  echo -e "Create a new site\n\nUsage:"
  echo "  new [domain]              Create new site"
  echo "  new [domain] [folder]     Create new child site"
  echo
  exit
fi

SCRIPTPATH=$(dirname $(readlink -f "$0"))
. $SCRIPTPATH/common

DOMAIN_NAME=$1
SUBFOLDER=$2

if [ -z "$SUBFOLDER" ]; then

  echo "Creating site at $DOMAIN_NAME"
  enter-when-ready

  sudo site $DOMAIN_NAME -wp -force-redirect=root
  sudo httpauth $DOMAIN_NAME -wp-admin=off &> /dev/null

  ln -s ~/www/$DOMAIN_NAME/htdocs ~/apps/$DOMAIN_NAME

  echo -e "\nSite installed at ~/apps/$DOMAIN_NAME"

  exit
fi


# Subfolder of existing site

echo "Creating child site at $DOMAIN_NAME/$SUBFOLDER"
enter-when-ready

if [ ! -L ~/apps/$DOMAIN_NAME ]; then
  echo "Site not found: ~/apps/$DOMAIN_NAME"
  exit
fi

sudo site $DOMAIN_NAME -subfolder=/$SUBFOLDER -wp -force-redirect=root # www -> root domain
sudo httpauth $DOMAIN_NAME -subfolder=/$SUBFOLDER -wp-admin=off &> /dev/null
