#!/bin/bash

# Get absolute path this script is in, for example: /home/$USER/bin
SCRIPTPATH=$(dirname $(readlink -f "$0"))

if [ -f $SCRIPTPATH/"$@" ]; then
  $SCRIPTPATH/"$@"
else
  if [ ! -z "$1" ]; then
    echo -e "Unknown command: $1\n"
  fi
  $SCRIPTPATH/help
fi
