#!/bin/bash

echo -e "Update system\n"

SCRIPTPATH=$(dirname $(readlink -f "$0"))
. $SCRIPTPATH/common

if [ "$1" == "webinoly" ]; then

  sudo rm -rf /opt/webinoly/lib
  sudo rm -rf /opt/webinoly/plugins
  sudo rm -rf /opt/webinoly/templates

  sudo cp -r $SCRIPTPATH/assets/webinoly/lib /opt/webinoly
  sudo cp -r $SCRIPTPATH/assets/webinoly/plugins /opt/webinoly
  sudo cp -r $SCRIPTPATH/assets/webinoly/templates /opt/webinoly

  sudo mkdir -p /opt/webinoly/templates/source
  sudo find /opt/webinoly -type d -exec chmod 755 {} \;
  sudo find /opt/webinoly -type f -exec chmod 644 {} \;
  sudo chmod -f 744 /opt/webinoly/lib/ex-*

  sudo chmod 755 /opt/webinoly/plugins/*
  sudo cp /opt/webinoly/plugins/* /usr/bin/

  sudo webinoly -update

fi
